In [41]:
import utils 
from tensorflow import keras
import pathlib
from  tensorflow.keras.metrics import mean_squared_error
import numpy as np


# LSTM

**Prepare data**

In [44]:
df = utils.load_and_clean_master_dataset()

df_train, df_val, df_test = utils.split_train_test_val(df)

X_train, y_train = utils.split_Xy(df_train)
X_val, y_val = utils.split_Xy(df_val)
X_test, y_test = utils.split_Xy(df_test)

X_train, scaler = utils.normalize(X_train, train=True)
X_val, _ = utils.normalize(X_val, train=False, scaler=scaler)
X_test, _ = utils.normalize(X_test, train=False, scaler=scaler)

i =7
X_train, X_val, X_test = X_train[utils.cols[:i+1]], X_val[utils.cols[:i+1]], X_test[utils.cols[:i+1]]


X_train, y_train = utils.to_batch(X_train, y_train)
X_val, y_val = utils.to_batch(X_val, y_val)
X_test, y_test = utils.to_batch(X_test, y_test)

**Reload model**

In [45]:
crnt_dir = pathlib.Path('.').parent.resolve()
lstm_model = keras.models.load_model(crnt_dir/'lstm'/'model')

**Evaluate model**

In [46]:
y_pred_lstm = lstm_model(X_test)
mean_squared_error(y_test.to_numpy(), y_pred_lstm.numpy().reshape(-1))

<tf.Tensor: shape=(), dtype=float32, numpy=0.00086672825>

# Simple NN

**Prepare data**

In [35]:
df = utils.load_and_clean_master_dataset()

df_train, df_val, df_test = utils.split_train_test_val(df)

X_train, y_train = utils.split_Xy(df_train)
X_val, y_val = utils.split_Xy(df_val)
X_test, y_test = utils.split_Xy(df_test)

i = 4
X_train, X_val, X_test = X_train[utils.cols[:i+1]], X_val[utils.cols[:i+1]], X_test[utils.cols[:i+1]]


**Reload model**

In [36]:
crnt_dir = pathlib.Path('.').parent.resolve()
nn_model = keras.models.load_model(crnt_dir/'DNN'/'model')

**Evaluate model**

In [38]:
# Take into account sliding window of models
X_test, y_test = X_test[20:], y_test[20:]

y_pred_nn = nn_model(X_test)
mean_squared_error(y_test.to_numpy(), y_pred_nn.numpy().reshape(-1))

AttributeError: 'tuple' object has no attribute 'as_list'

# Transformer

**Prepare data**

In [12]:
df = utils.load_and_clean_master_dataset()

df_train, df_val, df_test = utils.split_train_test_val(df)

X_train, y_train = utils.split_Xy(df_train)
X_val, y_val = utils.split_Xy(df_val)
X_test, y_test = utils.split_Xy(df_test)

i = 4
X_train, X_val, X_test = X_train[utils.cols[:i+1]], X_val[utils.cols[:i+1]], X_test[utils.cols[:i+1]]

X_train, y_train = utils.to_batch(X_train, y_train)
X_val, y_val = utils.to_batch(X_val, y_val)
X_test, y_test = utils.to_batch(X_test, y_test)

**Reload model**

In [13]:
crnt_dir = pathlib.Path('.').parent.resolve()
transformer_model = keras.models.load_model(crnt_dir/'Transformer_model'/'best_transformer_model')

**Evaluate model**

In [14]:
y_pred_transformer = transformer_model(X_test)
mean_squared_error(y_test.to_numpy(), y_pred_transformer.numpy().reshape(-1))

<tf.Tensor: shape=(), dtype=float32, numpy=0.0004239239>

# Ensemble

In [48]:
y_pred = np.mean([y_pred_transformer,  y_pred_lstm], axis=0)
mean_squared_error(y_test.to_numpy(), y_pred.reshape(-1))

<tf.Tensor: shape=(), dtype=float32, numpy=0.00037183272>